-- ========================================
-- Non-AI Trading System Database Schema
-- Capital: ₹50,000
-- Tables: 12 (Core + Real-time + Options)
-- ========================================

-- ========================================
-- Table 1: Holdings Table
-- Tracks current open positions (swing trades)
-- ========================================
CREATE TABLE IF NOT EXISTS holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    position_type TEXT NOT NULL CHECK(position_type IN ('LONG', 'SHORT')),
    quantity INTEGER NOT NULL,
    entry_price REAL NOT NULL,
    entry_date TEXT NOT NULL,
    entry_time TEXT,
    strategy_name TEXT NOT NULL,
    stop_loss REAL NOT NULL,
    target REAL NOT NULL,
    current_price REAL,
    unrealized_pnl REAL DEFAULT 0,
    sector TEXT,
    last_updated TEXT NOT NULL,
    UNIQUE(symbol, position_type)
);

-- ========================================
-- Table 2: Trades Table
-- Complete trade history (BUY/SELL/SHORT/COVER)
-- ========================================
CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trade_id TEXT NOT NULL UNIQUE,
    symbol TEXT NOT NULL,
    trade_type TEXT NOT NULL CHECK(trade_type IN ('BUY', 'SELL', 'SHORT', 'COVER')),
    position_type TEXT NOT NULL CHECK(position_type IN ('SWING', 'INTRADAY')),
    quantity INTEGER NOT NULL,
    price REAL NOT NULL,
    trade_date TEXT NOT NULL,
    trade_time TEXT NOT NULL,
    strategy_name TEXT NOT NULL,
    realized_pnl REAL DEFAULT 0,
    charges REAL DEFAULT 0,
    net_pnl REAL DEFAULT 0,
    holding_days INTEGER DEFAULT 0,
    entry_price REAL,
    exit_price REAL,
    stop_loss REAL,
    target REAL,
    exit_reason TEXT,
    notes TEXT,
    created_at TEXT NOT NULL
);

-- ========================================
-- Table 3: Daily Portfolio Snapshot
-- EOD performance tracking
-- ========================================
CREATE TABLE IF NOT EXISTS daily_portfolio (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL UNIQUE,
    starting_capital REAL NOT NULL,
    ending_capital REAL NOT NULL,
    daily_pnl REAL NOT NULL,
    daily_pnl_percent REAL NOT NULL,
    cumulative_pnl REAL NOT NULL,
    cumulative_pnl_percent REAL NOT NULL,
    deployed_capital REAL NOT NULL,
    available_cash REAL NOT NULL,
    num_positions INTEGER DEFAULT 0,
    num_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    win_rate REAL DEFAULT 0,
    max_drawdown REAL DEFAULT 0,
    sharpe_ratio REAL DEFAULT 0,
    total_charges REAL DEFAULT 0,
    created_at TEXT NOT NULL
);

-- ========================================
-- Table 4: Signals Table
-- All signals generated by strategies
-- ========================================
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id TEXT NOT NULL UNIQUE,
    symbol TEXT NOT NULL,
    signal_type TEXT NOT NULL CHECK(signal_type IN ('BUY', 'SELL', 'SHORT', 'COVER')),
    strategy_name TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    signal_strength REAL NOT NULL CHECK(signal_strength BETWEEN 0 AND 100),
    current_price REAL NOT NULL,
    target_price REAL,
    stop_loss REAL,
    risk_reward_ratio REAL,
    indicator_values TEXT,
    signal_date TEXT NOT NULL,
    signal_time TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('PENDING', 'EXECUTED', 'REJECTED', 'EXPIRED')) DEFAULT 'PENDING',
    executed_at TEXT,
    rejection_reason TEXT,
    created_at TEXT NOT NULL
);

-- ========================================
-- Table 5: Strategy Performance Table
-- Per-strategy tracking and analytics
-- ========================================
CREATE TABLE IF NOT EXISTS strategy_performance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    strategy_name TEXT NOT NULL,
    period TEXT NOT NULL,
    total_signals INTEGER DEFAULT 0,
    executed_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    win_rate REAL DEFAULT 0,
    total_pnl REAL DEFAULT 0,
    avg_pnl_per_trade REAL DEFAULT 0,
    max_win REAL DEFAULT 0,
    max_loss REAL DEFAULT 0,
    avg_holding_days REAL DEFAULT 0,
    sharpe_ratio REAL DEFAULT 0,
    max_drawdown REAL DEFAULT 0,
    profit_factor REAL DEFAULT 0,
    last_updated TEXT NOT NULL,
    UNIQUE(strategy_name, period)
);

-- ========================================
-- Table 6: Risk Metrics Table
-- Daily risk tracking and limits
-- ========================================
CREATE TABLE IF NOT EXISTS risk_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL UNIQUE,
    daily_loss REAL DEFAULT 0,
    daily_loss_percent REAL DEFAULT 0,
    weekly_loss REAL DEFAULT 0,
    weekly_loss_percent REAL DEFAULT 0,
    monthly_drawdown REAL DEFAULT 0,
    monthly_drawdown_percent REAL DEFAULT 0,
    max_position_exposure REAL DEFAULT 0,
    total_exposure REAL DEFAULT 0,
    exposure_percent REAL DEFAULT 0,
    num_positions INTEGER DEFAULT 0,
    num_sectors INTEGER DEFAULT 0,
    sector_concentration TEXT,
    risk_limit_breached INTEGER DEFAULT 0,
    circuit_breaker_triggered INTEGER DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL
);

-- ========================================
-- Table 7: Market Data Cache
-- Recent OHLCV data for active symbols
-- ========================================
CREATE TABLE IF NOT EXISTS market_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL CHECK(timeframe IN ('1m', '5m', '15m', '1h', 'daily')),
    timestamp TEXT NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL,
    indicators TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(symbol, timeframe, timestamp)
);

-- ========================================
-- Table 8: Intraday Positions Table (NEW)
-- Active intraday positions with MIS
-- ========================================
CREATE TABLE IF NOT EXISTS intraday_positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    position_id TEXT NOT NULL UNIQUE,
    symbol TEXT NOT NULL,
    position_type TEXT NOT NULL CHECK(position_type IN ('LONG', 'SHORT')),
    quantity INTEGER NOT NULL,
    entry_price REAL NOT NULL,
    entry_time TEXT NOT NULL,
    strategy_name TEXT NOT NULL,
    stop_loss REAL NOT NULL,
    target REAL NOT NULL,
    trailing_sl REAL,
    current_price REAL,
    unrealized_pnl REAL DEFAULT 0,
    max_profit REAL DEFAULT 0,
    max_loss REAL DEFAULT 0,
    status TEXT NOT NULL CHECK(status IN ('OPEN', 'CLOSED')) DEFAULT 'OPEN',
    exit_price REAL,
    exit_time TEXT,
    exit_reason TEXT,
    realized_pnl REAL,
    charges REAL DEFAULT 0,
    net_pnl REAL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- ========================================
-- Table 9: Stop-Loss Tracker Table (NEW)
-- Real-time stop-loss monitoring
-- ========================================
CREATE TABLE IF NOT EXISTS stop_loss_tracker (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    position_id TEXT NOT NULL,
    symbol TEXT NOT NULL,
    position_type TEXT NOT NULL CHECK(position_type IN ('SWING', 'INTRADAY', 'OPTIONS')),
    sl_type TEXT NOT NULL CHECK(sl_type IN ('FIXED', 'TRAILING', 'PERCENTAGE', 'ATR', 'TIME_BASED')),
    initial_sl REAL NOT NULL,
    current_sl REAL NOT NULL,
    entry_price REAL NOT NULL,
    current_price REAL,
    high_since_entry REAL,
    low_since_entry REAL,
    trailing_percent REAL,
    atr_value REAL,
    time_based_exit TEXT,
    last_check_time TEXT,
    sl_hit INTEGER DEFAULT 0,
    sl_hit_time TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(position_id)
);

-- ========================================
-- Table 10: Options Positions Table (NEW)
-- Options trades and monitoring
-- ========================================
CREATE TABLE IF NOT EXISTS options_positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    position_id TEXT NOT NULL UNIQUE,
    underlying_symbol TEXT NOT NULL,
    option_type TEXT NOT NULL CHECK(option_type IN ('CE', 'PE')),
    strike_price REAL NOT NULL,
    expiry_date TEXT NOT NULL,
    strategy_type TEXT NOT NULL CHECK(strategy_type IN ('DIRECTIONAL_CALL', 'DIRECTIONAL_PUT', 'COVERED_CALL')),
    quantity INTEGER NOT NULL,
    lot_size INTEGER NOT NULL,
    entry_premium REAL NOT NULL,
    entry_date TEXT NOT NULL,
    entry_time TEXT NOT NULL,
    current_premium REAL,
    underlying_entry_price REAL,
    underlying_current_price REAL,
    unrealized_pnl REAL DEFAULT 0,
    stop_loss_percent REAL DEFAULT 0.45,
    target_percent REAL,
    days_to_expiry INTEGER,
    theta_decay REAL,
    status TEXT NOT NULL CHECK(status IN ('OPEN', 'CLOSED')) DEFAULT 'OPEN',
    exit_premium REAL,
    exit_date TEXT,
    exit_time TEXT,
    exit_reason TEXT,
    realized_pnl REAL,
    charges REAL DEFAULT 0,
    net_pnl REAL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- ========================================
-- Table 11: Multi-Timeframe Signals Table (NEW)
-- Signals across multiple timeframes for alignment
-- ========================================
CREATE TABLE IF NOT EXISTS multi_timeframe_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    daily_signal TEXT CHECK(daily_signal IN ('BUY', 'SELL', 'NEUTRAL')),
    h1_signal TEXT CHECK(h1_signal IN ('BUY', 'SELL', 'NEUTRAL')),
    m15_signal TEXT CHECK(m15_signal IN ('BUY', 'SELL', 'NEUTRAL')),
    m5_signal TEXT CHECK(m5_signal IN ('BUY', 'SELL', 'NEUTRAL')),
    m1_signal TEXT CHECK(m1_signal IN ('BUY', 'SELL', 'NEUTRAL')),
    alignment_score REAL NOT NULL CHECK(alignment_score BETWEEN 0 AND 100),
    final_signal TEXT CHECK(final_signal IN ('BUY', 'SELL', 'NONE')),
    confidence_level TEXT CHECK(confidence_level IN ('LOW', 'MEDIUM', 'HIGH')),
    daily_indicators TEXT,
    h1_indicators TEXT,
    m15_indicators TEXT,
    m5_indicators TEXT,
    m1_indicators TEXT,
    created_at TEXT NOT NULL,
    UNIQUE(symbol, date, time)
);

-- ========================================
-- Table 12: Order Queue Table (NEW)
-- Pending orders for execution
-- ========================================
CREATE TABLE IF NOT EXISTS order_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id TEXT NOT NULL UNIQUE,
    symbol TEXT NOT NULL,
    order_type TEXT NOT NULL CHECK(order_type IN ('BUY', 'SELL', 'SHORT', 'COVER')),
    position_type TEXT NOT NULL CHECK(position_type IN ('SWING', 'INTRADAY', 'OPTIONS')),
    quantity INTEGER NOT NULL,
    price_type TEXT NOT NULL CHECK(price_type IN ('MARKET', 'LIMIT')),
    limit_price REAL,
    strategy_name TEXT NOT NULL,
    stop_loss REAL,
    target REAL,
    signal_id TEXT,
    priority INTEGER DEFAULT 5,
    status TEXT NOT NULL CHECK(status IN ('PENDING', 'EXECUTING', 'EXECUTED', 'FAILED', 'CANCELLED')) DEFAULT 'PENDING',
    created_at TEXT NOT NULL,
    executed_at TEXT,
    execution_price REAL,
    failure_reason TEXT,
    retry_count INTEGER DEFAULT 0
);

-- ========================================
-- Indexes for Performance Optimization
-- ========================================

-- Holdings indexes
CREATE INDEX IF NOT EXISTS idx_holdings_symbol ON holdings(symbol);
CREATE INDEX IF NOT EXISTS idx_holdings_strategy ON holdings(strategy_name);

-- Trades indexes
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_date ON trades(trade_date);
CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades(strategy_name);
CREATE INDEX IF NOT EXISTS idx_trades_type ON trades(position_type);

-- Signals indexes
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(signal_date);
CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals(strategy_name);

-- Market data indexes
CREATE INDEX IF NOT EXISTS idx_market_data_symbol ON market_data(symbol);
CREATE INDEX IF NOT EXISTS idx_market_data_timeframe ON market_data(timeframe);
CREATE INDEX IF NOT EXISTS idx_market_data_timestamp ON market_data(timestamp);

-- Intraday positions indexes
CREATE INDEX IF NOT EXISTS idx_intraday_symbol ON intraday_positions(symbol);
CREATE INDEX IF NOT EXISTS idx_intraday_status ON intraday_positions(status);

-- Options positions indexes
CREATE INDEX IF NOT EXISTS idx_options_underlying ON options_positions(underlying_symbol);
CREATE INDEX IF NOT EXISTS idx_options_expiry ON options_positions(expiry_date);
CREATE INDEX IF NOT EXISTS idx_options_status ON options_positions(status);

-- Multi-timeframe signals indexes
CREATE INDEX IF NOT EXISTS idx_mtf_symbol ON multi_timeframe_signals(symbol);
CREATE INDEX IF NOT EXISTS idx_mtf_date ON multi_timeframe_signals(date);

-- Order queue indexes
CREATE INDEX IF NOT EXISTS idx_orders_status ON order_queue(status);
CREATE INDEX IF NOT EXISTS idx_orders_priority ON order_queue(priority);
